from randomWalk import * 
from Grafo import *
from Nodo import *

g = Grafo(4)
n1 =  Nodo(0 ,0)
n2 =  Nodo(1 ,1)
n3 =  Nodo(2 ,0)
n4 =  Nodo(3 ,0)
n5 =  Nodo(4 ,0)
n6 =  Nodo(5 ,0)
n7 =  Nodo(6 ,0)
n8 =  Nodo(7 ,0)
g.addNode(n1)
g.addNode(n2)
g.addNode(n3)
g.addNode(n4)
g.addEdge((n1,n2))
g.addEdge((n2,n3))
g.addEdge((n3,n4))
g.addEdge((n1,n3))
g.addEdge((n4,n1))
g.addEdge((n2,n4))
g.showAdjacencyMatrix()
g.showDegreeMatrix()
rw = randomWalk(g)
rw.showWalkMatrix()
rw.showp0()
rw.showpi()
a =rw.getStationaryState()
print(a)
rw.showpi()